name = "leanq"
version = "0.1.0"
defaultTargets = ["leanq"]

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries"
rev = "main"

[[lean_lib]]
name = "Leanq"

[[lean_exe]]
name = "leanq"
root = "Main"
